Repository shoekstra/repo-settings, pull requests merged in 2023-05, with the labels that each got.

#15 misc: Add labels and release drafter
  .github/labels.yaml
  .github/workflows/label-synchronization.yaml
  .github/workflows/pr-validation.yaml
  .github/workflows/release-drafter.yaml
  .github/workflows/update-changelog.yaml
  .goreleaser.yml
Labels: misc

#16 fix: can't update archived/read-only projects
  internal/gitlab/group.go
Labels: fix

#17 chore: Build all images with `goreleaser`
  .gitignore
  .goreleaser.yml
  Dockerfile
  Dockerfile.alpine
  Dockerfile.goreleaser
Labels: chore

#18 chore: Fix checkout token
  .github/workflows/update-changelog.yaml
Labels: bug

#19 chore: go mod tidy
  go.mod
  go.sum
Labels: chore
